package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import org.junit.jupiter.api.Test;

import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.05 13:10:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {


  // Generated by ComTest BEGIN
  /** testToString112 */
  @Test
  public void testToString112() {    // Peli: 112
    Peli peli = new Peli(); 
    peli.parse("1|11|WIN|12|2|3|43|33|RANKED"); 
    assertEquals("From: Peli line: 115", "1|11|WIN|12|2|3|43|33|RANKED", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Peli: 139
    Peli peli = new Peli(); 
    peli.parse("1|11|WIN|12|2|3|43|33|RANKED"); 
    assertEquals("From: Peli line: 142", 1, peli.getId()); 
    assertEquals("From: Peli line: 143", "1|11|WIN|12|2|3|43|33|RANKED", peli.toString()); 
  } // Generated by ComTest END
}